### ISSUE TITLE
No X11 DISPLAY

### ISSUE THREAD

**Issue by anthonygreen** [dhoer/chef-sikulix#3]
Running
`sudo chef-client` 
on a node with sikulix in it's run-list I get
`No X11 DISPLAY variable was set, but this program performed an operation which requires it.`

**Comment by anthonygreen** [comment]
It is Ubuntu 14.04
 
The stack trace is:
https://gist.github.com/anthonygreen/bf3d54986f5d23a68975

**Comment by dhoer** [comment]
Thanks for the stack trace.  This is due to setup having no options selected, so it runs the default GUI setup.  By default, all options are set to false.  Since there are a variety of options to choose from, you must set desired option(s) to true.  

The setup recipe now warns 'SikuliX setup has no options selected - nothing to do' when no options are set to true and skips setup  .  I also updated the readme to be more clear on how to use this recipe.  

This functionality is in release v2.0.2.
